spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true

server:
  port: 8765

eureka:
  client:
    defaultZone: http://localhost:8761/eureka