server:
  port: 8888 # Default port for Spring Cloud Config Server
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EduardoSampaio/microservices-config-server
          search-paths:
          - greeting-service
